services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=shopply_db'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"