#services:
#  user-service:
#    container_name: user-service
#    image: mysql
#    volumes:
#      - ./mysql_user_data:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: users
#      MYSQL_USER: seguser
#      MYSQL_PASSWORD: password
#
#  product-service:
#    container_name: product-service
#    image: 'mongo:latest'
#    restart: unless-stopped
#    ports:
#      - "27017:27017"
#    expose:
#      - "27017"
#    volumes:
#      - ./product-data:/data/db

