# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI for Portfolio-api

on:
  push:
    branches: 
      - 'main' 
    paths: 
      - 'portfolio-app/Portfolio-backend/**'
  pull_request:
    branches: 
      - 'main'
    paths: 
      - 'portfolio-app/Portfolio-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Build docker image
      run: docker build -t portfolio-api:latest app

    - name: Push docker image to hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag my-spring-boot-app:latest $DOCKER_USERNAME/my-spring-boot-app:latest
        docker push $DOCKER_USERNAME/my-spring-boot-app:latest

  deploy:
    runs-on: ubuntu-lastest
    needs: build
    
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Deploy with docker compose
      run: |
        docker-compose -f app/docker-compose.yml up -d
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
